__default__:
  jobname: "{rule}.{wildcards}"
  nodes: 1
  ntaskspernode: 1
  cpuspertask: 1
  mempercpu: "1gb"
  time: "24:00:00"
  #partition: "standard"
  mailuser: "zl338@duke.edu" # ENTER EMAIL BETWEEN QUOTES
  mailtype: "END,FAIL"
  output: "logs/%x-%j.out"

# modify config for certain rules
plot_histogram:
  time: "10:00"

