# Config file for running euroformix using snakemake pipeline

# Input file pathnames, change if needed
# See README for more information on formatting input files
hu_allele_freqs_csv: 'data/Hu_allele_freq.csv' # Human population allele frequencies; csv required
hum_profiles_csv: 'data/STR_human_database_long.csv' # human STR profiles; csv required
moz_profiles_csv: 'data/STR_all_mozzies_long.csv' # mosquito STR profiles; csv required

# Default output file path names 
outfile: 'output/log10LRs.csv' # csv output

# Other parameters
kit: "GenePrint10" # STR kit name
threads: 4 # number of threads to use when calculating LRs

